version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile.app
    working_dir: /app
    volumes:
      - ./webroot:/app
    networks:
      - debug-network
    environment:
      PHP_IDE_CONFIG: "serverName=127.0.0.1"

  presentation:
    build:
      context: ./docker
      dockerfile: Dockerfile.presentation
    working_dir: /app
    volumes:
      - ./webroot:/app
    ports:
      - 8082:80
    networks:
      - debug-network

  database:
    image: mysql:5.7
    command: --max_allowed_packet=52505856
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=recruit"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33062:3306"
    networks:
      - debug-network

  queue:
    image: recruit_cv_app
    command: php artisan queue:work
    volumes:
      - ./webroot:/app
    restart: always
    networks:
      - debug-network

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - debug-network

  websocket-server:
    build:
      context: ./docker
      dockerfile: Dockerfile.websocket
    volumes:
      - ./webroot:/app
    ports:
      - "6001:6001"
    depends_on:
      - redis
    networks:
      - debug-network

volumes:
  dbdata:

networks:
  debug-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
